bookapp/urls.py
from django.urls import path,re_path
from bookapp import views
app_name = 'bookapp'
urlpatterns = [
    path('index/',views.index,name='index'),
    path('booklist/',views.booklist,name='booklist'),
    path('book_details/',views.book_details,name='book_details'),
    path('book_sort/',views.book_sort,name='book_sort'),
]

userapp/urls.py
from django.urls import path
from userapp import views
app_name = 'userapp'
urlpatterns = [
    path('register/',views.register,name='register'),
    path('check_email/',views.check_email,name='check_email'),
    path('generate_code/',views.generate_code,name='generate_code'),
    path('check_code/',views.check_code,name='check_code'),
    path('activate_user/',views.activate_user,name='activate_user'),
    path('registerlogic/',views.registerlogic,name='registerlogic'),
    path('login/',views.login,name='login'),
    path('loginlogic/',views.loginlogic,name='loginlogic'),
    path('login_jump',views.login_jump,name='login_jump'),
    path('logout/',views.logout,name='logout'),
]

userapp/views.py
import datetime
import hashlib,random,string
import time,uuid

from django.core.mail import EmailMultiAlternatives
from django.db import transaction
from django.shortcuts import render,redirect,HttpResponse
from django.urls import reverse

from bookapp.models import TUser,ConfirmCode
# Create your views here.
from userapp.captcha.image import ImageCaptcha


def register(request):
    # current_id用来判断用户是在index,booklist,book_details的哪个也页面发起的请求
    current_id = request.GET.get('current_id','0')
    request.session['current_id'] = current_id
    # cato_one_id = request.GET.get('cato_one_id')
    # cato_two_id = request.GET.get('cato_two_id')
    # page_num = request.GET.get('page_num')
    # request.session['current_id'] = current_id
    # request.session['cato_one_id'] = cato_one_id
    # request.sesson['cato_two_id'] = cato_two_id
    # request.session['page_num'] = page_num
    return render(request,'userapp/register.html')


def check_email(request):
    """
    用户注册时，验证用户的邮箱是否已在数据库中，若不在，证明可用
    :param request:
    :return:
    """
    text_email = request.POST.get('text_email')
    # return render(request,'userapp/register_ok.html')
    return HttpResponse('no') if TUser.objects.filter(email=text_email) else HttpResponse('ok')


def generate_code(request):
    image = ImageCaptcha()
    content = ''.join(random.sample(string.ascii_letters,4))
    print(content)
    request.session['code'] = content
    data = image.generate(content)
    return HttpResponse(data,'image/png')


def process_pwd(pwd,salt=None):
    h = hashlib.md5()
    if not salt:
        salt = ''.join(random.sample(string.ascii_letters,5))
    h.update((pwd+salt).encode())
    return salt,h.hexdigest()


def check_code(request): # 前端的 ajax 请求，判断验证码输入是否正确
    text_code = request.GET.get('text_code')
    session_code = request.session.get('code')
    # session_code = request.session.get('login_code') if 'login' in request.path else request.session.get('code')
    if(text_code.lower() == session_code.lower()):
        return HttpResponse('ok')
    return HttpResponse('no')


def generate_confirmcode():
    """
    产生邮箱验证码
    :return:
    """
    time_string = datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    h = hashlib.md5()
    h.update(time_string.encode())
    print(h.hexdigest())
    return h.hexdigest()


def send_confirmEmail(confirm_code,user_id,email):
    """
    给用户发送激活用户的邮件
    :param confirm_code:
    :param user_id:
    :return:
    """
    subject, from_email, to = 'This is Derek',  'derekdongsir@sina.com',email,
    text_content = 'Hi,this is from Derek'
    html_content = '<p>感谢注册<a href="http://{}/userapp/activate_user/?code={}&user_id={}"target = blank > www.baidu.com < / a >，\欢迎你来验证你的邮箱，验证结束你就可以登录了！ < / p > '.format('127.0.0.1:8000',confirm_code,user_id)
    msg = EmailMultiAlternatives(subject, text_content, from_email, [to])
    msg.attach_alternative(html_content, "text/html")
    msg.send()


def activate_user(request):
    """
    用户点击该链接以激活状态
    :param request:
    :return:
    """
    code = request.GET.get('code')
    user_id = request.GET.get('user_id')
    if ConfirmCode.objects.filter(code=code):
        user =TUser.objects.get(id=user_id)
        user.status = True
        user.save()
        return HttpResponse('ok')
    return HttpResponse('failed')


def registerlogic(request):
    time.sleep(2)
    id = str(uuid.uuid4())
    email = request.POST.get('txt_email')
    name = request.POST.get('txt_name')
    password = request.POST.get('txt_password')
    repassword = request.POST.get('txt_repassword')
    if password == repassword: # 再确认从前端传递过来的密码是否一致
        salt,password = process_pwd(password) # 获得盐和加密后的密码
        # request.session['user_id'] = id #将用户的id存储进session,便于后续使用
        # request.session['username'] = name # 将用户昵称保存在 session中，表示用户已登录，同时便于取出显示在主页面
        user=TUser(id=id,email=email,password=password,nick_name=name,salt=salt)
        user.save()
        confirm_code = generate_confirmcode() #产生邮箱验证码
        ConfirmCode.objects.create(code=confirm_code,user=user)
        send_confirmEmail(confirm_code,id,email) # 给用户发送激活邮件
        return render(request, 'userapp/register_ok.html',{'email':email}) # 注册成功，返回注册成功的页面
    return HttpResponse('密码不一致')


def login(request): #渲染登录界面
    #依据发送登录请求的页面的不同，渲染不同的页面给用户
    # '1':booklist,'2':book_detail,'3':购物车页面  默认为index
    current_id = request.GET.get('current_id','0')
    request.session['current_id'] = current_id #存进session,便于 jump时候使用
    return render(request,'userapp/login.html')


def loginlogic(request):
    email = request.POST.get('email')
    password = request.POST.get('password')
    auto_login = request.POST.get('auto_login') # 值为真则设置cookie记住密码
    try:
        user= TUser.objects.get(email=email)
        if user.password == process_pwd(password,salt=user.salt)[1]:
            if user.status: #判断用户是否处于激活状态
                request.session['username'] = user.nick_name # 将用户昵称存入session，代表用户已登录
                request.session['user_id'] = user.id  # 将用户的id存储进 session
                return HttpResponse('ok')
            return HttpResponse('dead')
        return HttpResponse('no') # 用户存在但是密码不对，返回no
    except: #用户不存在返回 no
       return HttpResponse('no')


def login_jump(request):
    order_confirmed = request.session.get("order_confirmed")
    if not order_confirmed: #如果此时订单未确认，则进一步判断用户处于哪一页
        current_id = request.session.get('current_id')
        if current_id == '1':
            cato_one_id = str(request.session.get('cato_one_id'))
            cato_two_id  = str(request.session.get('cato_two_id'))
            page_num = str(request.session.get('page_num'))
            # url1 ="bookapp/booklist/?cato_one_id="+cato_one_id+'&cato_two_id='+cato_two_id+'&page_num='+page_num
            return redirect("bookapp:booklist")
        elif current_id == '2': #代表从书籍详情页发起的登录
            return redirect('bookapp:book_details')
        elif current_id == '3': # 代表从购物车页面发起登录
            return redirect('orderapp:cart_page')
        else:
            return redirect('bookapp:index')
    return redirect('orderapp:indent')#进入地址填写页面


def logout(request): #使用Ajax请求进行登出，将用户名从session中清除即可
    if request.session.get('username') and request.session.get('user_id'):
        if request.session.get("order_confirmed"): #将订单确认标志删除
            del request.session["order_confirmed"]
        if request.session.get('cart'):
            del request.session['cart'] #将购物车清除
        del request.session['username']
        del request.session['user_id']
    return HttpResponse('no') if request.session.get('username') else HttpResponse('ok')

templates/userapp/register_ok.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>当当</title>
<link type="text/css" href="/static/css/register_150706.css" rel="stylesheet">
<link href="/static/css/unite_header_1129.css" rel="stylesheet" type="text/css">
<script src="/static/js/zhuce/pagetop_20121010.js"type="text/javascript"></script>
    <script>
        var t = 6;
        myInterval = setInterval(function () {
            if(t){
                t --;
                document.getElementById('em').innerText = t;
            }
        },1000);
        setTimeout(function () {
            clearInterval(myInterval);
            location.href = "{% url 'userapp:login' %}";
            },6000);
    </script>
</head>
<body>
<div class="ddnewhead_wrap">
    <div class="ddnewhead_content ddnewhead_content2">
        <div class="ddnewhead_operate" id="__ddnav_menu">
          
{#          <p id="nickname">欢迎光临当当网，请<a name="ddnav_login" href="{% url 'userapp:login' %}" target="_self" class="login_link">登录</a>#}
{#              <a name="ddnav_register" href="{% url 'userapp:register' %}" target="_self" class="login_link">免费注册</a></p>#}
    </div>
              <div class="ddnewhead_logo">
                  <a href="http://www.dangdang.com" title="返回首页" name="ddnav_logo">
                      <img src="/static/images/zc_logo.jpg" alt="百知网"></a></div>
      <div class="clear"></div>
    </div>
     <div class="ddnewcarthead_bottom"></div>
</div>
<form id="register_form" method="post" action="#" onsubmit="return false;">
        	<input style="display: none;" type="password">
            <div id="bd">
				<!--默认-->
				<div class="shadow_box">
					<div class="register_box">
						<div class="head">
							<span class="dd_more">
                                <a href="{% url 'bookapp:index' %}" class="home">当当首页</a><a href="http://help.dangdang.com/details/page2">注册帮助</a></span>
							<a href="javascript:void(0);" class="head_a head_a1">新用户注册</a>
							<!--<a href="register_company.php?returnurl=http://book.dangdang.com/" class="head_a">企业用户注册</a>-->
						</div>
						<div class="body zccg">
							<p>恭喜您，注册成功！</p>
                            <ul><li class="first">邮箱</li>
                            <li class="last">{{ email }}</li>
                            </ul>
{#                            <div class="zccg_btn"><a href="{% url 'bookapp:index' %}">立即购物</a>#}
                            <div class="zccg_btn"><a href="{% url 'userapp:login' %}">立即登录</a>
                                <span><em id="em">6</em>秒后自动前往……</span>
                                <span></span>
                                <span>我们已向您的邮箱发送了激活链接，请尽快激活您的账户</span>
                            </div>
						</div>
					</div>
				</div>
			</div>
            <input id="btn_confirm" style="display: none" type="submit">
			<input name="hdn_username" id="hdn_username" type="hidden">
			<input name="hdn_mobile" id="hdn_mobile" type="hidden">
			<input name="hdn_password" id="hdn_password" type="hidden">
			<input name="action_post" id="action_post" value="register" type="hidden">
			<input name="returnurl" id="returnurl" value="http://book.dangdang.com/" type="hidden">
        </form>
        <style type="text/css">
    .footer_nav_box{border-top: 1px solid #ebebeb;width:100%;_width:expression(this.scrollWidth < 960 ? "960px" : "auto");min-width: 960px;padding: 17px 0 50px;}
    .footer_nav_box a,.footer_nav_box{color: #8c8c8c;font-size: 12px;text-decoration: none;}
    .footer_nav_box a:hover{color: #f48570;text-decoration: underline;}
    .footer_nav_box .footer_nav{text-align: center;line-height: 20px;padding-bottom: 17px;padding-top: 25px;}
    .footer_nav_box .footer_nav span.sep{margin: 0 17px 0 19px;}
    .footer_nav_box .footer_copyright{line-height: 20px;text-align: center;width: 960px;margin: 0 auto;}
    .footer_nav_box .footer_copyright span.sep{margin:0 17px 0 19px;}
    .footer_nav_box .footer_icon{padding: 10px 0 0 340px;width: 640px;margin: 0 auto;height: 77px;}
    .footer_nav_box .validator,.footer_nav_box .knet{float:left;display:inline;padding:15px 5px 15px;width:135px;height:47px;}

    .footer_copyright {padding: 10px 0 0 0; margin: 0 auto;float: none; width: auto;text-align: center;color: #8c8c8c;}
    .footer_copyright span, .public_footer .footer_copyright a.footer_img { display: inline-block; float: none; }
    .footer_copyright a { padding: 0 4px; color: #8c8c8c;font-size: 12px;text-decoration: none;}
    .footer_copyright a:hover{color: #f48570;text-decoration: underline;}
    .footer_nav_box .footer_nav .footer_hot_search{display:inline-block;*display:inline;width:50px;position:relative}
    .footer_nav_box .footer_nav .pos_a_box{position:absolute;left:-251px;top:22px;background-color:#f48570;width:300px;border-radius:8px;text-align:center;height:14px;line-height:14px}
    .footer_nav_box .footer_nav .pos_a_box a,.footer_nav_box .footer_nav .pos_a_box a:hover,.footer_nav_box .footer_nav .pos_a_box span{padding:0 2px;color:#fff;text-decoration:none}
    .footer_nav_box .footer_nav .pos_a_box i{display:block;width:0;height:0;line-height:0;font-size:0;border-width:0 4px 4px;border-style:solid;border-color:#fff #fff #f48570 #fff;position:absolute;right:20px;top:-4px}
</style>
<div class="footer_nav_box">
    <div class="footer_nav"><a href="http://static.dangdang.com/topic/2227/176801.shtml" target="_blank" rel="nofollow">公司简介</a><span class="sep">|</span><a href="http://ir.dangdang.com/" target="_blank">Investor Relations</a><span class="sep">|</span><a href="http://zhaopin.dangdang.com" target="_blank">诚聘英才</a><span class="sep">|</span><a href="http://static.dangdang.com/topic/744/200778.shtml" target="_blank">手机当当</a><span class="sep">|</span><a href="http://union.dangdang.com/" target="_blank">网站联盟</a><span class="sep">|</span><a href="http://outlets.dangdang.com/merchants_open" target="_blank">当当招商</a><span class="sep">|</span><a href="http://misc.dangdang.com/groupbuy/Default.aspx" target="_blank" rel="nofollow">机构销售</a><span class="sep">|</span><a href="http://blog.dangdang.com/" target="_blank">官方Blog</a>
        <script>
            var setTo = null;
            function showghotsearch() {
                clearTimeout(setTo);
                document.getElementById("hot_search_content").style.display = "block";
            }
            function hidehotsearch() {
                setTo = setTimeout(function() {
                    document.getElementById("hot_search_content").style.display = "none";
                }, 100)
            }
        </script>   		
    </div>
    <div class="footer_copyright"><span>Copyright (C) 当当网 2004-2017, All Rights Reserved</span></div>
    <div class="footer_copyright"><span><a href="http://www.miibeian.gov.cn/" target="_blank" rel="nofollow">京ICP证041189号</a></span><span class="sep">|</span><span>出版物经营许可证 新出发京批字第直0673号</span><span class="sep">|</span><span>食品流通许可证：SP1101011010021855(1-1)</span><br><span>互联网药品信息服务资格证编号：(京)-非经营性-2012-0016</span><span class="sep">|</span><span>京公网安备110101000001号</span></div>
    <!-- 有三个icon的时候加footer_icon2 -->
    <div class="footer_icon footer_icon2" style="padding-left: 55px;">
        <div class="validator"><a href="http://www.hd315.gov.cn/beian/view.asp?bianhao=010202001051000098" target="_blank" class="footer_img"><img src="/static/images/validate.gif"></a></div>
        <div class="knet"><!-- 可信网站LOGO安装开始 -->
            <script type="text/JavaScript">
                function CNNIC_change(eleId) {
                var str = document.getElementById(eleId).href;
                var str1 = str.substring(0, (str.length - 6));
                str1 += CNNIC_RndNum(6);
                document.getElementById(eleId).href = str1;
                }

                function CNNIC_RndNum(k) {
                var rnd = "";
                for (var i = 0; i < k; i++)
                rnd += Math.floor(Math.random() * 10);
                return rnd;
                }
            </script>
            <a href="https://ss.knet.cn/verifyseal.dll?sn=2010091900100002234&amp;pa=2940051" tabindex="-1" id="urlknet" target="_blank" rel="nofollow"><img alt="可信网站" name="CNNIC_seal" src="/static/images/knetSealLogo.png" oncontextmenu="return false;" onclick="CNNIC_change('urlknet')" width="128" height="47" border="true"></a><!-- 可信网站LOGO安装结束 -->
        </div>
        <div class="validator"><a href="http://bj429.com.cn/" target="_blank" class="footer_img"><img src="/static/images/7d593c48-48f6-4fc9-85e0-7d6e10dfc2a2.hpvgUvc9"></a></div>
        <div class="validator"><a id="_pingansec_bottomimagesmall_brand" href="http://si.trustutn.org/info?sn=302161014024825726885&amp;certType=1" target="_blank"><img src="/static/images/brand_128_47.png"></a></div>
        <div class="clear"></div>
    </div>
</div>
</body>
</html>