bookapp/urls.py
from django.urls import path,re_path
from bookapp import views
app_name = 'bookapp'
urlpatterns = [
    path('index/',views.index,name='index'),
    path('booklist/',views.booklist,name='booklist'),
    path('book_details/',views.book_details,name='book_details'),
    path('book_sort/',views.book_sort,name='book_sort'),
]

manageapp/urls.py
from django.urls import path
from manageapp import views
app_name ='manageapp'
urlpatterns = [
    path('index/',views.index,name='index'),
    path('booklist/',views.booklist,name='booklist'),
    path('delete_book/',views.delete_book,name="delete_book"),
    path('mass_delete/',views.mass_delete,name='mass_delete'),
    path('add_book/',views.add_book,name='add_book'),
    path('add_book_logic/',views.add_book_logic,name='add_book_logic'),
    path('add_book_type/',views.add_book_type,name='add_book_type'),
    path('add_book_type_logic/',views.add_book_type_logic,name='add_book_type_logic'),
    path('add_parent_type/',views.add_parent_type,name='add_parent_type'),
    path('add_parent_type_logic/',views.add_parent_type_logic,name='add_parent_type_logic'),
    path('book_id/',views.book_id,name='book_id'),
    path('location/',views.location,name='location'),
    path('add_location/',views.add_location,name='add_location'),
    path('add_location_logic/',views.add_location_logic,name='add_location_logic'),
    path('catogray_num-pie/',views.catogray_num_pie,name='catogray_num_pie'),# 图书数量大饼图
]

manageapp/models.py
from django.db import models

# Create your models here.

manageapp/views.py
import uuid

from django.core.paginator import Paginator
from django.http import JsonResponse
from django.shortcuts import render,redirect,HttpResponse
from pyecharts.charts import Pie,Page
from pyecharts import options as opts

from bookapp.models import BookInfo,TDelivery,TCatogray,TOrder
# Create your views here.

def index(request):
    return render(request,'manageapp/index.html')


def booklist(request):
    all_books = BookInfo.objects.all()
    book_id = request.GET.get('book_id') # 从 book_id页面通过点击 更多 进入此页面
    if book_id:
        all_books = BookInfo.objects.filter(id=book_id) # 此时，仅显示被选中的书籍
    page_num = int(request.GET.get('page_num',1)) #在booklist页面内进行跳转
    """
    :return: 将联合查询的书籍的种类名作为键，书籍作为值，构成字典传递到前端
    """
    # books ={book.catogray.catogry_name:book for book in BookInfo.objects.all()}
    paginator = Paginator(all_books,per_page=20)
    page = paginator.page(page_num)
    book_dic = {book.catogray.catogry_name:book for book in page}
    return render(request, 'manageapp/bookIist.html',{'page':page,'book_dic':book_dic})

def delete_book(request):
    book_id = request.GET.get('book_id')
    book = BookInfo.objects.get(id=book_id)
    # book.delete()
    return HttpResponse('ok')

def mass_delete(request):
    '''接收前端传递的拼接后的id字符串，进行拆分，取出单个id'''
    ids = request.GET.get('ids')
    id_ls =ids.split('/') #获得书籍的id列表
    return HttpResponse('ok')


def add_parent_type(request):
    return render(request,'manageapp/add_parent_type.html')


def add_parent_type_logic(request):
    '''接收到的父类名称,查询数据库该名称是否已经存在，不存在则添加'''
    type_name = request.GET.get('type_name') # 将父类名称添加入类别库中
    if TCatogray.objects.filter(catogry_name=type_name):
        return HttpResponse('failed')
    #由于建表时采用integer作为primary key数据类型，因而此时不能使用 uuid 来生成 id
    return HttpResponse('ok')


def add_book_type(request):
    parents = request.session.get('parents')
    if not parents:
        parents = TCatogray.objects.filter(parent_id=None)
        request.session['parents'] = parents
    return render(request,'manageapp/add_book_type.html',{"parents":parents})


def add_book_type_logic(request):
    type_name = request.GET.get('t_name')
    num = request.GET.get('number')
    parent_id = int(request.GET.get('parent'))
    if TCatogray.objects.filter(parent_id=parent_id,catogry_name=type_name):
        return HttpResponse('failed')
    return HttpResponse('ok')


def book_id(request):
    page_num = int(request.GET.get('page_num',1))
    paginator = Paginator(BookInfo.objects.all(),per_page=15)
    page = paginator.page(page_num)
    return render(request,'manageapp/book_id.html',{'page':page})


def add_book(request):
    catogray = request.session.get('sub_catogray')
    if not catogray:
        catogray = TCatogray.objects.filter(parent_id__isnull=False)#筛选出所有的二级类
        request.session['sub_catogray'] = catogray
    return render(request,'manageapp/add_book.html',{'catogray':catogray})


def add_book_logic(request):
    book_name = request.GET.get('book_name')
    author = request.GET.get('author')
    press = request.GET.get('press')
    catogray_id = request.GET.get('catogray_id')
    publish_time = request.GET.get('publish_time')
    # print(catogray_id)
    return HttpResponse('ok')


def location(request):
    page_num = int(request.GET.get('page_num',1))
    locations = request.session.get('locations')
    if not locations:
        locations = TDelivery.objects.filter(torder__create_time__isnull=False) #筛选出创建过订单的用户地址信息
        request.session['locations'] = locations
    paginator = Paginator(locations,per_page=10)
    page = paginator.page(page_num)
    location_dict ={ location.torder_set.all()[0].create_time:location for location in page }
    return render(request,'manageapp/location.html',{'page':page,'location_dict':location_dict})


def add_location(request):
    return  render(request,'manageapp/add_location.html')

def add_location_logic(request):
    location_id = request.GET.get("location_id")
    user_name = request.GET.get("user_name")
    receiver = request.GET.get("receiver")
    phone = request.GET.get("phone")
    crate_time = request.GET.get("crate_time")
    send_time = request.GET.get("send_time")
    receive_time = request.GET.get("receive_time")
    return HttpResponse('ok')


def catogray_num_pie(request):
    '''
     #catogray 是一个一级类的字典，键为 类id，每个键对应的值为一个列表
            #列表第一项为该类下共有多少本图书，第二项为类名,第三项为该类对应的二级类字典
            #二级类字典 键为 类id，值为列表，列表第一项为该二级类下的书的数量，第二项为类名
    '''
    catogray = request.session.get('catogray')
    def pie_base() -> Pie:
        c = (
            Pie()
                .add("", [[item[1],item[0]] for item in catogray.values()])
                .set_global_opts(title_opts=opts.TitleOpts(title="图书类别统计"))
                .set_series_opts(label_opts=opts.LabelOpts(formatter="{b}: {c}"))
        )
        return c
    c = pie_base()
    return HttpResponse(c.render_embed()) # 将一级类图书类别和数量以大饼图的形式内嵌在网页中

templates/manageapp/add_book.html
<style>
	.table1{
		border-color: lightgray;
	}
	.td1,.td2{
		height: 36px;
	}
	.td1{
		text-align: right;
		padding-right: 5px;
		background-color: rgb(230,242,254);
		font-size: 14px;
	}
	.td2{
		padding-left: 5px;
	}
</style>
<form id='my_form' action="{% url 'manageapp:add_book_logic' %}" method="get">
<table class="table1" border="1" cellspacing="0" width="1110px">
	<tr>
		<td class="td1">商品名称:</td>
		<td class="td2"><input id="book_name"  name="book_name" type="text" /></td>
	</tr>
	<tr>
		<td class="td1">作者:</td>
		<td class="td2"><input name='author' type="text"  id="author"/></td>
	</tr>
	<tr>
		<td class="td1">出版社:</td>
		<td class="td2"><input id='press' type="text" name="press" /></td>
	</tr>
	<tr>
		<td class="td1">商品类别:</td>
		<td class="td2">
			<select id="catogray_id" name="catogray_id">
				<option value='type'>商品类别</option>
                {% for type in catogray %}
                    <option value="{{ type.id }}">{{ type.catogry_name }}</option>
                {% endfor %}
			</select>
		</td>
	</tr>
	<tr>
		<td class="td1">出版日期:</td>
		<td class="td2">
			<input type="date" id="publish_time" name="publish_time"/>
		</td>
	</tr>
    <tr>
		<td class="t2" colspan="2" style="padding-left: 24%;" >
			<input type="button" onclick="my_submit()" value="提交" />
			<input type="button" onclick="my_reset()" value="重置"/>
		</td>
	</tr>
</table>
</form>
<script src="/static/jquery/jquery.1.8.3.min.js"></script>
<script>
    function my_reset() {
        $("#book_name").val(null);
        $("#author").val(null);
        $("#press").val(null);
        $("#publish_time").val(null);
        $("#catogray_id").val(null);
    }
    function my_submit() {
        if(!$("#book_name").val()){
            alert('请填写书名！')
        }else if(!$("#catogray_id").val()){
            alert('请选择类别！')
        }else if(!$("#author").val()){
            alert('请填写作者')
        }else if(!$("#press").val()){
            alert('请填写出版社！')
        }else if(! $("#publish_time").val()){
            alert('请选择出版日期！')
        }else{
            $("#my_form").submit()
        }
    }
</script>

templates/manageapp/add_book_type.html
<style>
	.table1{
		border-color:rgba(180,207,207,0.4);
	}
	.td1,.td2{
		height: 36px;
	}
	.td1{
		text-align: right;
		padding-right: 5px;
		background-color: rgb(230,242,254);
		font-size: 14px;
	}
	.td2{
		padding-left: 5px;
	}	
</style>
<form id='my_form' action="{% url 'manageapp:add_book_type_logic' %}" method="get">
<table class="table1" border="1" cellspacing="0" width="1110px">
	<tr>
		<td class="td1">子类名称:</td>
		<td class="td2"><input id='t_name' name='t_name' type="text" /></td>
	</tr>
	<tr>
		<td class="td1">子类数量:</td>
		<td class="td2"><input id='number' name="number" type="text" /></td>
	</tr>
	<tr>
		<td class="td1">父类名称:</td>
		<td class="td2">
			<select id="parent_id" name="parent">
				<option value="parent">父类名</option>
                {% for catogray in parents %}
                    <option value="{{ catogray.id }}">{{ catogray.catogry_name }}</option>
                {% endfor %}
			</select>
		</td>
	</tr>
	<tr>
		<td style="padding-left: 24%;" colspan="2">
			<input type="button" onclick="my_submit()" value="提交" />
			<input type="button" onclick="my_reset()" value="重置"/>
		</td>
	</tr>
</table>
</form>
<script src="/static/jquery/jquery.1.8.3.min.js"></script>
<script>
    function my_submit() {
        if(!$("#t_name").val()){   alert('请填写类别名！') }
        else if(!$("#number").val()){   window.alert('请填写数量！')}
        else if($("#parent_id").val() === 'parent'){
         window.alert('请选择父类');
        }else {
            $("#my_form").submit();
        }
    }
    function my_reset() {
        $("#t_name").val(null);
        $("#number").val(null);
        $("#parent_id").val("父类名");
    }
</script>

templates/manageapp/add_location.html
<style>
	.table1{
		border-color: lightgray;
	}
	.td1,.td2{
		height: 36px;
	}
	.td1{
		text-align: right;
		padding-right: 5px;
		background-color: rgb(230,242,254);
		font-size: 14px;
	}
	.td2{
		padding-left: 5px;
	}
</style>
<form id='my_form' action="{% url 'manageapp:add_location_logic' %}" method="get">
<table class="table1" border="1" cellspacing="0" width="1110px">
	<tr>
		<td class="td1">地址id:</td>
		<td class="td2"><input id="location_id"  name="location_id" type="text" /></td>
	</tr>
    <tr>
		<td class="td1">用户名:</td>
		<td class="td2"><input id="user_name"  name="user_name" type="text" /></td>
	</tr>
	<tr>
		<td class="td1">收件人:</td>
		<td class="td2"><input name='receiver' type="text"  id="receiver"/></td>
	</tr>
	<tr>
		<td class="td1">手机号:</td>
		<td class="td2"><input id='phone' type="text" name="phone" /></td>
	</tr>

	<tr>
		<td class="td1">创建时间:</td>
		<td class="td2">
			<input type="date" id="crate_time" name="create_time"/>
		</td>
	</tr>
    	<tr>
		<td class="td1">发货时间:</td>
		<td class="td2">
			<input type="date" id="send_time" name="send_time"/>
		</td>
	</tr>
    	<tr>
		<td class="td1">收获时间:</td>
		<td class="td2">
			<input type="date" id="receive_time" name="receive_time"/>
		</td>
	</tr>

    <tr>
		<td class="t2" colspan="2" style="padding-left: 24%;" >
			<input type="button" onclick="my_submit()" value="提交" />
			<input type="button" onclick="my_reset()" value="重置"/>
		</td>
	</tr>
</table>
</form>
<script src="/static/jquery/jquery.1.8.3.min.js"></script>
<script>
    function my_reset() {
        $("#location_id").val(null);
        $("#user_name").val(null);
        $("#receiver").val(null);
        $("#phone").val(null);
        $("#crate_time").val(null);
        $("#send_time").val(null);
        $("#receive_time").val(null);
    }
    function my_submit() {
        if( !$("#location_id").val()){
            window.alert('请填写地址id');
        } else if(!$("#user_name").val()){
            alert('请填写用户名！')
        }else if(!$("#receiver").val()){
            alert('请填写收货人姓名！')
        }else if(!$("#phone").val()){
            alert('请填写手机号')
        }else if(!$("#crate_time").val()){
            alert('请选择创建时间！')
        }else if(! $("#send_time").val()){
            alert('请选择发货日期！')
        }else if(! $("#receive_time").val()){
            alert('请选择收货日期！')
        } else{
            $("#my_form").submit()
        }
    }
</script>

templates/manageapp/add_parent_type.html
<style>
	.t1{
		text-align: right;
		padding-right: 5px;
		background-color: rgb(230,242,254);
		width: 46%;
		font-size: 12px;
	}
	.t2{
		height: 30px;
		padding-left: 42%;
		
	}
	.t1,.t2{
		height: 30px;
	}
</style>
<table border="1" cellspacing="0" style="width: 100%;border-color:rgba(180,207,207,0.4)">
	<tr>
		<td class="t1">父类名称：</td>
		<td style="padding-left: 4px;"><input id='t_name' type="text" /></td>
	</tr>
	<tr>
		<td class="t2" colspan="2">
			<input type="button" onclick="my_submit()" value="提交" />
			<input type="button" onclick="my_reset()" value="重置"/>
		</td>
	</tr>
</table>
<script src="/static/jquery/jquery.1.8.3.min.js"></script>
<script>
    function my_reset(){
        $("#t_name").val(null);
    }
    function my_submit() {
        var name = $("#t_name").val();
        if(name){
            $.ajax({
               type:'get',
               data:"type_name="+name,
               url:"{% url 'manageapp:add_parent_type_logic' %}",
              success:function (res) {
                if(res ==='ok'){   window.alert('添加成功！') }
                else{   window.alert("该类别已存在！")    }
              }
            });
        }else{
            alert('提交内容不能为空！')
        }
    }
</script>

templates/manageapp/bookIist.html
<style>
	.d1{
		background-color: rgb(53,60,68);
		position: relative;
		height: 30px;
		line-height: 30px;
		padding-left: 10px;
	}
	.s1{
		font-size: 12px;
		color: white;
	}
	.s2{
		position: absolute;
		right: 10px;
	}
	.s2 a{
		color: white;
		font-size: 12px;
		text-decoration: none;
	}
	.t1{
		border-color:aliceblue;
		margin-top: 2px;
		font-size: 12px;
		text-align: center;
		background-color: rgb(230,242,254);
	}
	.bottom{
		font-size: 13px;
		padding-left: 15px;
		position: relative;
	}
	.bs{
		position: absolute;
		right: 40px;
	}
	.bs a{
		text-decoration: none;
		color: black;
	}
	.bs a:hover{
		color: cornflowerblue;
		text-decoration: underline;
	}
</style>
<div class="d1">
	<span class="s1">管理人员基本信息表</span>
	<span class="s2">
		<a href="{% url 'manageapp:add_book' %}">添加</a>
		<a href="javascript:void(0)" onclick="mass_delete()">删除</a>
	</span>
</div>
<table border="2" width="100%" cellspacing="0" class="t1" id="b_table">
	<tr>
		<td><input type="checkbox" onclick="choose_all(this)"/></td>
		<td>商品ID</td>
		<td>商品名称</td>
		<td>作者</td>
		<td>出版社</td>
		<td>市场价</td>
		<td>当当价</td>
		<td>库存</td>
		<td>商品种类</td>
		<td>基本操作</td>
	</tr>
    {% for catogray,book in book_dic.items %}
        <tr id="tr{{ book.id }}">
        <td><input id="box{{ book.id }}" type="checkbox" name="checkbox" value="{{ book.id }}"/></td>
		<td>{{ book.id }}</td>
		<td>{{ book.book_name }}</td>
		<td>{{ book.author }}</td>
		<td>{{ book.press }}</td>
		<td>{{ book.marketing_price }}</td>
		<td>{{ book.dangdang_price }}</td>
		<td>{{ book.stock }}</td>
		<td>{{ catogray }}</td>
		<td>
            <a href="javascript:void(0)" onclick="b_delete({{ book.id }})">删除</a>
		    <a href="javascript:void(0)" onclick="b_modify({{ book.id }})">修改</a>
        </td>
	</tr>
    {% endfor %}

</table>
<div class="bottom">
	共有 {{  page.paginator.count}}条记录，当前第{{ page.number }} 页，共{{ page.paginator.num_pages }} 页
	<span class="bs">
        {% if page.has_previous %}
            <a href="{% url 'manageapp:booklist' %}?page_num={{ page.previous_page_number }}" style="margin-right: 20px;">上一页</a>
        {% else %}
            <a href="javascript:void(0)" style="margin-right: 20px;">上一页</a>
        {% endif %}
        {% if page.has_next %}
            <a href="{% url 'manageapp:booklist' %}?page_num={{ page.next_page_number }}" style="margin-right: 20px;">下一页</a>
        {% else %}
            <a href="javascript:void(0)" style="margin-right: 20px;">下一页</a>
        {% endif %}
	</span>
</div>
<script src="/static/jquery/jquery.1.8.3.min.js"></script>
<script>
    function choose_all(self) {
        var value = $(self).attr('checked');
        if(value ==='checked'){
            $("input[name='checkbox']").attr("checked",'true');
        }else{
             $("input[name='checkbox']").removeAttr('checked');
        }
    }
    function mass_delete() {
        alert('您确定要删除所有选中书籍吗？');
        var id_list =[];
        $("input[name='checkbox']:checkbox:checked").each(function(){
            var book_id = $(this).val();
            id_list.push(book_id);
            $("#tr"+book_id).remove();
        });
        {#alert(id_list.join('/'))#}
        $.ajax({
            type:'get',
            data:'ids='+id_list.join('/'),
            url:"{% url 'manageapp:mass_delete' %}"
        })
    }

    function b_delete(book_id){
        var box = $("#box"+book_id).attr('checked');
        if(box ==='checked'){
            alert("确定要删除选中的书籍吗？");
            $.ajax({
                type:'get',
                data:'book_id='+book_id,
                url:"{% url 'manageapp:delete_book' %}",
                success:function (res) {
                      {#移除自身#}
                        $("#tr"+book_id).remove();
                        alert('书籍成功删除');
                }
            })
        }else{  alert("请先选中书籍！")}
    }

    function b_modify(book_id){
        alert('此功能暂不实现');
    }
</script>

templates/manageapp/book_id.html
<style>
	.d1{
		background-color: rgb(53,60,68);
		position: relative;
		height: 30px;
		line-height: 30px;
		padding-left: 10px;
	}
	.s1{
		font-size: 12px;
		color: white;
	}
	.s2{
		position: absolute;
		right: 10px;
	}
	.s2 a{
		color: white;
		font-size: 12px;
		text-decoration: none;
	}
	.t1{
		border-color:aliceblue;
		margin-top: 2px;
		font-size: 12px;
		text-align: center;
		background-color: rgb(230,242,254);
	}
	.bottom{
		font-size: 13px;
		padding-left: 15px;
		position: relative;
	}
	.bs{
		position: absolute;
		right: 40px;
	}
	.bs a{
		text-decoration: none;
		color: black;
	}
	.bs a:hover{
		color: cornflowerblue;
		text-decoration: underline;
	}
</style>
<div class="d1">
	<span class="s1">商品管理</span>
	<span class="s2">
		<a href="#">添加</a>
		<a href="#">删除</a>
	</span>
</div>
<table border="2" width="100%" cellspacing="0" class="t1">
	<tr>
		<td>商品ID</td>
		<td>商品名称</td>
		<td>更多</td>
	</tr>
    {% for book in page %}
     <tr>
		<td>{{ book.id }}</td>
		<td>{{ book.book_name }}</td>
		<td><a href="javascript:void(0)" onclick="details({{ book.id }})">更多</a></td>
	</tr>
    {% endfor %}
</table>
<div class="bottom">
	共有 {{ page.paginator.count }}条记录，当前第{{ page.number }} 页，共{{ page.paginator.num_pages }} 页
	<span class="bs">
        {% if page.has_previous %}
            <a href="{% url 'manageapp:book_id' %}?page_num={{ page.previous_page_number }}" style="margin-right: 20px;">上一页</a>
        {% else %}
            <a href="javascript:void(0)" style="margin-right: 20px;">上一页</a>
        {% endif %}
        {% if page.has_next %}
            <a href="{% url 'manageapp:book_id' %}?page_num={{ page.next_page_number }}" style="margin-right: 20px;">下一页</a>
        {% else %}
            <a href="javascript:void(0)" style="margin-right: 20px;">下一页</a>
        {% endif %}
	</span>
</div>
<script>
    function details(book_id) {
        location.href = "{% url 'manageapp:booklist' %}?book_id="+book_id;
    }
</script>

templates/manageapp/index.html
<!DOCTYPE HTML>
<html>
 <head>
  <title>商品管理系统</title>
   <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
   <link href="/static/manage/css/dpl-min.css" rel="stylesheet" type="text/css" />
   <link href="/static/manage/css/bui-min.css" rel="stylesheet" type="text/css" />
   <link href="/static/manage/css/main-min.css" rel="stylesheet" type="text/css" />
 </head>
 <body>
	<div class="header">
	    <div class="dl-title">
	        <span class="lp-title-port">BZ</span><span class="dl-title-text">商品管理系统</span>
	       </a>
	     </div>
	    <div class="dl-log">欢迎您，<span class="dl-log-user">管理员</span>
	    	<a href="#" title="退出系统" class="dl-log-quit">[退出]</a>
	    	<a href="#" title="文档库" class="dl-log-quit">文档库</a>
	    </div>
	</div>
    <div class="content">
    <div class="dl-main-nav">
      <div class="dl-inform"><div class="dl-inform-title">贴心小秘书<s class="dl-inform-icon dl-up"></s></div></div>
      <ul id="J_Nav"  class="nav-list ks-clear">
        <li class="nav-item dl-selected"><div class="nav-item-inner nav-home">首页</div></li>
      </ul>
    </div>
    <!--
    	重点！！！
    	用以引入Scriptz中的数据
    -->
    <ul id="J_NavContent" class="dl-tab-conten"></ul>
   </div>
   <!-- BUI框架，做网站的导航栏 -->
  <script type="text/javascript" src="/static/manage/js/jquery-1.8.1.min.js"></script>
  <script type="text/javascript" src="/static/manage/js/bui.js"></script>
  <script type="text/javascript" src="/static/manage/js/config.js"></script>
{#    这一行非常重要，否则 common/main无法使用#}
    <script src="/static/manage/js/common/main.js"></script>
  <script>
    BUI.use('common/main',function(){
      var config = [{
          id:'menu', 
          homePage : 'code',
          menu:[{
              text:'商品管理',
              items:[
                {id:'code',text:'增加商品',href:'{% url 'manageapp:add_book' %}',closeable : false},
                {id:'main-menu',text:'商品列表',href:'{% url 'manageapp:booklist' %}'},
                {id:'quick',text:'商品数量统计',href:'{% url 'manageapp:catogray_num_pie' %}'},
              ]
            },{
              text:'商品类别管理',
              items:[
                {id:'operation',text:'增加商品父类别',href:"{% url 'manageapp:add_parent_type' %}"},
                {id:'quick',text:'增加商品子类别',href:'{% url 'manageapp:add_book_type' %}'},
                {id:'quick',text:'商品类别列表',href:'{% url 'manageapp:book_id' %}'}
              ]
            },{
              text:'地址管理',
              items:[
                {id:'resource',text:'地址列表',href:'{% url 'manageapp:location' %}'},
                {id:'quick',text:'增加地址信息',href:'{% url 'manageapp:add_location' %}'}
              ]
            }]
          }];
         new PageUtil.MainPage({
         modulesConfig : config
      });
    });
  </script>
<div style="display:none">
    <script src='http://v7.cnzz.com/stat.php?id=155540&web_id=155540'
                                  language='JavaScript' charset='utf-8'>

    </script>
</div>
</body>
</html>

templates/manageapp/location.html
<style>
	.d1{
		background-color: rgb(53,60,68);
		position: relative;
		height: 30px;
		line-height: 30px;
		padding-left: 10px;
	}
	.s1{
		font-size: 12px;
		color: white;
	}
	.s2{
		position: absolute;
		right: 10px;
	}
	.s2 a{
		color: white;
		font-size: 12px;
		text-decoration: none;
	}
	.t1{
		border-color:aliceblue;
		margin-top: 2px;
		font-size: 12px;
		text-align: center;
		background-color: rgb(230,242,254);
	}
	.bottom{
		font-size: 13px;
		padding-left: 15px;
		position: relative;
	}
	.bs{
		position: absolute;
		right: 40px;
	}
	.bs a{
		text-decoration: none;
		color: black;
	}
	.bs a:hover{
		color: cornflowerblue;
		text-decoration: underline;
	}
</style>
<div class="d1">
	<span class="s1">订单管理</span>
	<span class="s2">
		<a href="{% url 'manageapp:add_location' %}">添加</a>
		<a href="javascript:void(0)" onclick="mass_delete()">删除</a>
	</span>
</div>
<table border="2" width="100%" cellspacing="0" class="t1">
	<tr>
		<td>
			<input type="checkbox" id="select_all" onclick="box_all()" />
		</td>
		<td>地址ID</td>
		<td>用户名</td>
		<td>创建时间</td>
		<td>发货时间</td>
		<td>收货时间</td>
		<td>收件人</td>
		<td>手机号</td>
	</tr>
    {% for create_time,location in location_dict.items %}
        <tr id="tr{{ location.id }}">
		<td>
			<input type="checkbox" name='box' value="{{ location.id }}"/>
		</td>
		<td>{{ location.id }}</td>
		<td>{{ location.user.nick_name }}</td>
		<td>{{ create_time |date:'Y/m/d H:i:s'}}</td>
		<td>{{create_time |date:'Y/m/d H:i:s'  }}</td>
		<td>unknown</td>
		<td>{{ location.receiver_name }}</td>
		<td>{{ location.phone }}</td>
	</tr>
    {% endfor %}

</table>
<div class="bottom">
	共有 {{ page.paginator.count }}条记录，当前第{{ page.number }} 页，共{{ page.paginator.num_pages }} 页
	<span class="bs">
		 {% if page.has_previous %}
            <a href="{% url 'manageapp:location' %}?page_num={{ page.previous_page_number }}" style="margin-right: 20px;">上一页</a>
        {% else %}
            <a href="javascript:void(0)" style="margin-right: 20px;">上一页</a>
        {% endif %}
        {% if page.has_next %}
            <a href="{% url 'manageapp:location' %}?page_num={{ page.next_page_number }}" style="margin-right: 20px;">下一页</a>
        {% else %}
            <a href="javascript:void(0)" style="margin-right: 20px;">下一页</a>
        {% endif %}
	</span>
</div>
<script src="/static/jquery/jquery.1.8.3.min.js"></script>
<script>
    function mass_delete() {
        var l_list =[];
        $("input[name='box']:checked").each(function () {
            var l_id = $(this).val();
            l_list.push(l_id);
            $("#tr"+l_id).remove();
        });
    }
    function box_all() {
        if($("#select_all").attr('checked')){
            $("input[name='box']").attr('checked','true');
        }else{
            $("input[name='box']").removeAttr('checked');
        }
    }
</script>